STAI_tibble <- tibble(
  text = c(
    "I.feel.calm",
    "I.feel.secure",
    "I.am.tense",
    "I.feel.strained",
    "I.feel.at.ease",
    "I.feel.upset",
    "I.am.presently.worrying.over.possible.misfortunes",
    "I.feel.satisfied",
    "I.feel.frightened",
    "I.feel.comfortable",
    "I.feel.self.confident",
    "I.feel.nervous",
    "I.am.jittery",
    "I.feel.indecisive",
    "I.am.relaxed",
    "I.feel.content",
    "I.am.worried",
    "I.feel.confused",
    "I.feel.steady",
    "I.feel.pleasant",
    "I.feel.pleasant",
    "I.feel.nervous.and.restless",
    "I.am.satisfied.with.myself",
    "I.wish.I.could.be.as.happy.as.others.seem.to.be",
    "I.feel.like.a.failure",
    "I.feel.rested",
    "I.am..cool..calm.and.collected",
    "I.feel.that.difficulties.are.piling.up.so.that.I.cannot.overcome.them",
    "I.worry.too.much.over.something.that.really.doesn.t.matter",
    "I.am.happy",
    "I.have.disturbing.thoughts",
    "I.lack.self.confidence",
    "I.feel.secure",
    "I.make.decisions.easily",
    "I.feel.inadequate",
    "I.am.content",
    "Some.unimportant.thoughts.run.through.my.mind.and.it.bothers.me",
    "I.take.disappointments.so.keenly.that.I.can.t.put.them.out.of.my.mind",
    "I.am.a.steady.person",
    "I.get.in.a.state.of.tension.or.turmoil.as.I.think.over.my.recent.concerns.and.interests",
  ),
  item = c(
    "STAI01", "STAI02", "STAI03", "STAI04", "STAI05", "STAI06", "STAI07", "STAI08", "STAI09", "STAI10", 
    "STAI11", "STAI12", "STAI13", "STAI14", "STAI15", "STAI16", "STAI17", "STAI18", "STAI19", "STAI20", 
    "STAI21", "STAI22", "STAI23", "STAI24", "STAI25", "STAI26", "STAI27", "STAI28", "STAI29", "STAI30", 
    "STAI31", "STAI32", "STAI33", "STAI34", "STAI35", "STAI36", "STAI37", "STAI38", "STAI39", "STAI40"
  )
)
